name: Build and Deploy
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build project
        run: npm run build
      - name: Deploy project
        run: |
          git config --global user.name 'MME Bot'
          git config --global user.email 'mme-bot@users.noreply.github.com'
          git add docs/
          git commit -am "Automated deploy"
          git push